export const GET_USER_NAME = 'GET_USER_NAME';
export const GET_PASSWORD = 'GET_PASSWORD';
export const LOADING = 'LOADING';
export const GET_SUPPORT = 'GET_SUPPORT';
export const AUTO_RESERVE = 'AUTO_RESERVE';
export const GET_SUPPORT_MESSAGE = 'GET_SUPPORT_MESSAGE';
export const GET_UNIVERSITY = 'GET_UNIVERSITY';
export const ADMIN_SEND_MESSAGE = 'ADMIN_SEND_MESSAGE';
